### ISSUE TITLE
Update 1.6.X please?

### ISSUE THREAD

**Issue by connerbw** [facile-it/doctrine-mysql-come-back#12]
Can you version this change please?

https://github.com/facile-it/doctrine-mysql-come-back/commit/3943d0c0908dc554aa486f68c070010a02ea9e28

Current composer version doesn't detect the string `PDO::query(): MySQL server has gone away`

**Comment by peelandsee** [comment]
dear @connerbw ,
as reported here yesterday
https://github.com/facile-it/doctrine-mysql-come-back/pull/11#issuecomment-219553469
the new version will be tagged during this week.

we prefer to delay it few days to let some tester check new behaviors and fix them if needed.
if you have an emergency in production, you can reference that commit hash in your composer.json as reported in https://getcomposer.org/doc/04-schema.md#package-links .

so, update your composer.json like this
```
"facile-it/doctrine-mysql-come-back": "dev-master#d3460870a7f3dbcab74ed9e84155a3b85cbc1474",
```
or wait until the end of the week..

bye!

**Comment by connerbw** [comment]
Ok. Thanks!
