### ISSUE TITLE
Statement object looses state of statement

### ISSUE THREAD

**Issue by dmifedorenko** [facile-it/doctrine-mysql-come-back#28]
Hello.

Check out catch code inside Statement::execute method. Then the connection is lost the $this->stmt property recreated without its internal state -- without binded params and variables, without fetch mode.

So this code with doctrine-mysql-come-back use will not wok correct:
```
$connection = baza::getService('master_connection');
$st = $connection->prepare('show variables like "wait_timeout"');
$st->setFetchMode(\Doctrine\DBAL\FetchMode::STANDARD_OBJECT);
$st->execute();
var_dump($st->fetchAll());
```

Without reconnect it will return object, and with reconnect where will be array. This is dangerous and not obvious behavior.

**Comment by peelandsee** [comment]
@dmifedorenko thanks for opening this and for providing an example code.

are you interested in creating a test-case / pr for fixing this issue?

thanks again,

**Comment by dmifedorenko** [comment]
I think about this but looks like there is no clean and simple way to fix it. The mysqli_stmt object linked with connection which is broken then "mysql has gone away" error rices. So you must recreate the ResultStatement object and call all its methods (like setFetchMode) second time. I cant imaging how we can fix it.

Object cloning would not work because cloned object will be linked with broken connection link. I my own project I wrapped all code with "for" and "try|catch" statements to make several tries.

My be you can write information about this problem in readme.md? This note can help overs.
