### ISSUE TITLE
ReflectionException: Property _transactionNestingLevel does not exist

### ISSUE THREAD

**Issue by starred-gijs** [facile-it/doctrine-mysql-come-back#31]
The [renaming a private property](https://github.com/doctrine/dbal/commit/1cbadb3e4821f10db4eb17b93dc3eed487751231#diff-7b1e94fb7dd408985f7b7973330dc2edR120) in `Doctrine\DBAL\Connection` breaks the reflection property name in
`$reflection->getProperty('_transactionNestingLevel');`

 https://github.com/facile-it/doctrine-mysql-come-back/blob/master/src/Connection.php#L272

Want me to make a PR?

**Comment by Jean85** [comment]
Yes, please!

For the record, this affects DBAL 2.9.0+

**Comment by starred-gijs** [comment]
Yes, indeed. Shall I bump that in the composer.json file, or try to create a solution that is backwards compatible?  Not sure how to defect DBAL version is possible? or try/catch the ReflectionException?

**Comment by Jean85** [comment]
Even better, we can use the `hasProperty` on the reflection, to avoid triggering an exception.

Doing a bump could be a problem, because it would trigger a patch bump on our side, and cut off any possibility of patching other bugs while supporting DBAL 2.8.
