### ISSUE TITLE
Usage of PrimaryReadReplicaConnection is failing

### ISSUE THREAD

**Issue by mordilion** [facile-it/doctrine-mysql-come-back#49]
When I am using the PrimaryReadReplicaConnection class to set up a Primary/Replica connection, then I am facing the following issue:

`Argument 2 passed to Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Statement::__construct() must be an instance of Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connection, instance of Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\PrimaryReadReplicaConnection given, called in vendor/facile-it/doctrine-mysql-come-back/src/ConnectionTrait.php on line 212 and defined in vendor/facile-it/doctrine-mysql-come-back/src/Statement.php:40`

My guess is that the Statement actually needs ConnectionInterface as the second parameter instead of Connection.

I am using the latest version `1.10.0`.

**Comment by mordilion** [comment]
Yes, that would solve the issue.

**Comment by thomasvargiu** [comment]
The hotifx is merged and [published in 1.10.1](https://github.com/facile-it/doctrine-mysql-come-back/releases/tag/1.10.1)
