### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by amigian74** [facile-it/doctrine-mysql-come-back#52]
Hi.

Unfortunately, the current version lacks new functions

for instance:
Call to undefined method Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Statement::executeQuery()

composer/package-versions-deprecated 1.11.99.1 
doctrine/annotations                 1.12.1    
doctrine/cache                       1.11.0    
doctrine/collections                 1.6.7     
doctrine/common                      3.1.2     
doctrine/dbal                        2.13.1    
doctrine/deprecations                v0.5.3    
doctrine/doctrine-bundle             2.3.2     
doctrine/event-manager               1.1.1     
doctrine/inflector                   2.0.3     
doctrine/instantiator                1.4.0     
doctrine/lexer                       1.2.1     
doctrine/orm                         2.8.4     
doctrine/persistence                 2.1.0     
doctrine/sql-formatter               1.1.1     
facile-it/doctrine-mysql-come-back   v1.8      
friendsofphp/proxy-manager-lts       v1.0.3    
laminas/laminas-code                 3.4.1     
laminas/laminas-eventmanager         3.2.1     
laminas/laminas-zendframework-bridge 1.1.1     
monolog/monolog                      2.2.0     
paragonie/constant_time_encoding     v2.4.0    
paragonie/random_compat              v9.99.100 
php-amqplib/php-amqplib              v3.0.0    
php-amqplib/rabbitmq-bundle          2.6.0     
phpseclib/phpseclib                  3.0.8     
psr/cache                            1.0.1     
psr/container                        1.1.1     
psr/event-dispatcher                 1.0.0     
psr/log                              1.1.4     
symfony/cache                        v5.2.7    
symfony/cache-contracts              v2.4.0    
symfony/config                       v5.2.7    
symfony/console                      v5.2.7    
symfony/dependency-injection         v5.2.7    
symfony/deprecation-contracts        v2.4.0    
symfony/doctrine-bridge              v5.2.7    
symfony/dotenv                       v5.2.4    
symfony/error-handler                v5.2.7    
symfony/event-dispatcher             v5.2.4    
symfony/event-dispatcher-contracts   v2.4.0    
symfony/filesystem                   v5.2.7    
symfony/finder                       v5.2.4    
symfony/flex                         v1.12.2   
symfony/framework-bundle             v5.2.7    
symfony/http-client-contracts        v2.4.0    
symfony/http-foundation              v5.2.7    
symfony/http-kernel                  v5.2.7    
symfony/lock                         v5.2.6    
symfony/monolog-bridge               v5.2.7    
symfony/monolog-bundle               v3.7.0    
symfony/polyfill-intl-grapheme       v1.22.1   
symfony/polyfill-intl-normalizer     v1.22.1   
symfony/polyfill-mbstring            v1.22.1   
symfony/polyfill-php73               v1.22.1   
symfony/polyfill-php80               v1.22.1   
symfony/proxy-manager-bridge         v5.2.4    
symfony/routing                      v5.2.7    
symfony/service-contracts            v2.4.0    
symfony/string                       v5.2.6    
symfony/var-dumper                   v5.2.7    
symfony/var-exporter                 v5.2.7    
symfony/yaml                         v5.2.7

**Comment by thomasvargiu** [comment]
Hi @amigian74,

It should be resolved with the 1.10 version. Update the library and try it.

**Comment by amigian74** [comment]
I wanted to try out the new version, but why is PHP 7.3 now a requirement for that - no other package needs PHP 7.3?

**Comment by thomasvargiu** [comment]
Because we released it for dbal 2.11, that was released for php >= 7.3. I just saw that they change it again later. We can try to do the same. I'm opening a new issue.

**Comment by amigian74** [comment]
Thx, that would be great
