### ISSUE TITLE
PHP 7.1 compatibility

### ISSUE THREAD

**Issue by thomasvargiu** [facile-it/doctrine-mysql-come-back#53]
doctrine/dbal [2.11](https://github.com/doctrine/dbal/blob/2.11.0/composer.json) was released with php >= 7.3 compatibility, later (in [2.13.0](https://github.com/doctrine/dbal/blob/2.13.0/composer.json)) they change it again to php 7.1 minimum version. We should try to do the same.

**Comment by amigian74** [comment]
Hi. This is still an very unpleasant issue, because we are still using PHP 7.2 and we can't use the new Doctrine functions because of the PHP 7.3 dependency of this bundle. Where is the problem to go back to PHP 7.1?

**Comment by Jean85** [comment]
We happily accept PRs, if they will include adding the proper CI checks.
