### ISSUE TITLE
Installation of version 2.x is not working

### ISSUE THREAD

**Issue by amigian74** [facile-it/doctrine-mysql-come-back#60]
Hi,

I'm tryinf to install the newsest version oft this package using:

````
composer require facile-it/doctrine-mysql-come-back ^2.0   
````
as documentation says. Unfortunately it's not working

````
[InvalidArgumentException]
Could not find package facile-it/doctrine-mysql-come-back in a version matching "2.0" and a stability matching "dev".
````

Thx in advance for any help. Steven

**Comment by nesl247** [comment]
@Jean85 do you have any idea when you plan to release 2.0?

**Comment by Jean85** [comment]
We're not sure, because we haven't really tested it in production yet. Can you report any result in that regard?

**Comment by amigian74** [comment]
Hi,

the package is running on my development server a couple of days now. Since I've fixed my issues, there are no problems with it, but I'm just using a few functions.

But so far, everything looks good.

**Comment by Jean85** [comment]
Thanks for reporting back @amigian74! I just tagged [2.0.0-BETA1](https://github.com/facile-it/doctrine-mysql-come-back/releases/tag/2.0.0-BETA1) (with no further changes), please use it and report back any issue you can find!

**Comment by tourze** [comment]
> Thanks for reporting back @amigian74! I just tagged [2.0.0-BETA1](https://github.com/facile-it/doctrine-mysql-come-back/releases/tag/2.0.0-BETA1) (with no further changes), please use it and report back any issue you can find!

Is there any plan about the release time of 2.0 ?

**Comment by Jean85** [comment]
There are a couple of issues that do not give me confidence yet to do it: #66 #63 #65 #68

**Comment by kibertoad** [comment]
@Jean85 How confident are you about using Beta 2 in production?

**Comment by Jean85** [comment]
I'm pretty confident that it should be good enough. I think I'll ask my colleagues to start using it on Monday.

I'll close this, please open a new one if you find any further issues.
