### ISSUE TITLE
Configuration no longer applies when using DoctrineBundle 2.6.3 and newer when replicas configured

### ISSUE THREAD

**Issue by nesl247** [facile-it/doctrine-mysql-come-back#61]
See https://github.com/doctrine/DoctrineBundle/issues/1541 where it broke upstream

**Comment by nesl247** [comment]
The issue isn't in the driver but here: https://github.com/facile-it/doctrine-mysql-come-back/blob/656bd4592c705c88294802bc948fd87f66250d42/src/Connection.php#L35-L37. It needs to look at `$params['primary']['driverOptions']` instead.

**Comment by Jean85** [comment]
Ouch, I forgot about this issue when writing #69. I'll hop on this.

**Comment by Jean85** [comment]
I've fixed it in #70 and released it as [2.0.0-BETA3](https://github.com/facile-it/doctrine-mysql-come-back/releases/tag/2.0.0-BETA3)
