### ISSUE TITLE
No reconnect on "START TRANSACTION"

### ISSUE THREAD

**Issue by amigian74** [facile-it/doctrine-mysql-come-back#63]
Hi,

I'm working with the newest release 2.0.0-BETA1 a couple of weeks now and run into an issue with the function beginTransaction.

This function is the first function to call for my process after a waiting period (in which the MySql-Server is gone away). Sadly the function throws an error "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" instead of reconnectiong and retrying. After some debugging I've found out that this function is trying to catch a Doctrine\DBAL\Exception instead of an core exception (\Exception) like other functions do. But the beginTransaction-function from Doctrine is throwing ad PDOException so its not caught in your beginTransaction-function. I've tried to catch the core exception instead but sadly canTryAgain returns false.

I'm not sure what's going wrong here exactly, whether it's just a typing error or this is intentionally (executeStatement and executeQuery also catches Exception instead of \Excpetion).

FYI: executeQuery works fine with catching Doctrine\DBAL\Exception instead of an core exception (\Exception)

Hope you can have a look into that. Meanwhile I'll try a workaround.

Thx and greetings Steven

**Comment by Jean85** [comment]
@thomasvargiu can you take a look at this? I'm off for the next weeks...

**Comment by thomasvargiu** [comment]
`Doctrine\DBAL\Driver\PDO\Connection` doesn't convert every exception from PDO, then yes, we should probably handle every exception. I will take a closer look at it.

**Comment by Jean85** [comment]
Fixed in #68
